### ISSUE TITLE
Compressed tables in migrations

### ISSUE THREAD

**Issue by adamchainz** [adamchainz/django-mysql#146]
InnoDB's `ROW_FORMAT=COMPRESSED` would be useful to support. Need to consider if `innodb_strict_mode` is on and if the table actually _is_ ending up compressed.

**Comment by drwonky** [comment]
This would be a useful feature, COMPRESSED has been available since 5.6, though there are a few cases that you could get shot in the foot:
- instance is 5.5
- file-per-table is 0
- if innodb_strict_mode is disabled when the table is created, but is enabled after creation, then you ALTER the table with ROW_FORMAT=COMPRESSED *and* the user created the table with a row length > 8126 bytes

That latter one is the gotcha.  With strict mode off, Innodb will allow you to violate the 8126 byte row length limit, but with strict mode on it will enforce it.  If someone creates a table, but it's never been rebuilt until they set COMPRESSED, it could result in an error when the ALTER runs.

There is likely to be a requirement moving forward that strict mode must be enabled for high availability uses, though you can set it at a session level (which may not be sticky) and result in a broken replica server.

ROW_FORMAT is tricky, because the default value is not stored in the table on creation, so the table can be different than the global default value, thus if COMPRESSED is the "apply" state, "DYNAMIC" is the safest "unapply" state for RunSQL.

DYNAMIC is valid in 5.6 and later, so if COMPRESSED is available, then DYNAMIC is the best choice for disabling this feature.

5.6 only supports COMPRESSED file-per-table tablespace, 5.7+ supports system, general, and file-per-table COMPRESSED tables.  So if file-per-table is 0, you can't use COMPRESSED on 5.6.

**Comment by adamchainz** [comment]
Indeed the situation with `ROW_FORMAT=COMPRESSED` is complicated.

Since I wrote this issue I've used MariaDB, with its [page compression feature](https://mariadb.com/kb/en/innodb-page-compression/). This can be set globally for all newly created tables with `SET GLOBAL`, avoiding the requirement for any changes in migrations.

I'm not sure there's much value in adding something specific to `ROW_FORMAT=COMPRESSED` now.

**Comment by drwonky** [comment]
Innodb Page Compression is a MariaDB specific feature and does not derive from upstream MySQL.

It would be nice to have this feature for people that *know* what they want, you have no way of knowing if someone turned off strict mode, created a non-compliant table, then enabled strict mode and then wanted to set COMPRESSED.

Bottom line, just emit an exception if MySQL throws an exception in this case, otherwise check that strict mode is on and if not, perhaps throw an exception that strict mode is required.  The only check you can actually do is for strict mode, the rest is reacting to MySQL errors.

Django is less likely to produce schemas that would cause problems since it's a controlled environment.

Some people can still shoot themselves in the foot even with steel toed boots.

**Comment by adamchainz** [comment]
Django-MySQL already warns about strict mode being off: https://django-mysql.readthedocs.io/en/latest/checks.html#django-mysql-w001-strict-mode . Therefore I don't think we'd need to do anything about it specific to compressed tables.

**Comment by adamchainz** [comment]
I think we can close this issue and rely on per-database settings and custom migraitons. It's not that hard to use `RunSQL` to alter a table's format if required.
