### ISSUE TITLE
Error in JSONField if multiple databases are used including non MySQL databses

### ISSUE THREAD

**Issue by marco-santamaria** [adamchainz/django-mysql#280]
Hi, I have a project where I'm using two databases: a MySQL database and a MS SQL Server database.
If I don't use a JSONField everything works fine. But when I try to migrate a model using a JSONField i get the following error:

`File "/home/......../virtualenvs/seta_fs/lib/python3.4/site-packages/django_mysql/models/fields/json.py", line 79, in _check_mysql_version
    not connections[db].is_mariadb and
AttributeError: 'DatabaseWrapper' object has no attribute 'is_mariadb'`
 
It appears that the function _check_mysql_version loops all the database configured assuming that the attribute "is_mariadb" is defined. So when it checks the non MySQL database it fails.

I tried to fix this issue and I know that I should use MySQL instead of MariaDB. You can look at my attempt here:  https://github.com/marco-santamaria/django-mysql/commit/aa00dc0d200f462633b9a1528d19d78c52db6947

Do you have any advice?

Django Version: *e.g. Django 1.9.5*
Database and version used: *MariaDB 10.1.13*
Version: *Django-MySQL 1.0.8*

**Comment by adamchainz** [comment]
That looks like a legitimate issue! Make a PR with your commit (add yourself to AUTHORS and a line in HISTORY, and an explicit test maybe?) :)

One thing - in your commit you're fixing `DynamicField`, rather than `JSONField`, which would explain why the issue would persist??

Note that JSONField is MySQL 5.7+ ONLY and will not work on MariaDB!

**Comment by marco-santamaria** [comment]
In that commit I was trying to fix the problem for JSONField but running the tests it looked like the same problem is affecting the DynamicField. Unfortunately is not easy to fix all the tests after the changes I made, because to match my scenario I added a new sqlite3 database to the testapp and I would like that all the migrations required to test the MySQL functionality are not executed in that dummy database. The intended purpose of the routers was to avoid the migrations on the sqlite3 database, but is not working.

I was thinking that maybe  the _check_mysql_version function should perform the check only for the databases used by the app where the model that is using the JSONField (or DynamicField) is defined, instead of cycling on all the databases configured. Also it would be possible to avoid the check and catch some exception at an higher level in case someone is using a field with the wrong MySQL version. Sounds reasonable?

If you can give me some advice about how to fix the tests, I will make a PR.

**Comment by adamchainz** [comment]
> I was thinking that maybe the _check_mysql_version function should perform the check only for the databases used by the app where the model that is using the JSONField (or DynamicField) is defined, instead of cycling on all the databases configured.

Unfortunately this isn't possible in Django, since routing can be done by arbitrary code and isn't just 'per app' or 'per model'. In general the advice is to keep your database config relatively simple, so I'm fine with checking that all MySQL databases in the config are compatible. If someone's running their app on multiple MySQL versions they're going to cause more pain than just this check (which can be silenced in the usual Django way).

I don't know how to fix the tests off the top of my head but if you open up a PR I can have a look. I can't use your code until you submit a PR, since until that point it's not a contribution acceptable under the Django-MySQL license 👍

**Comment by marco-santamaria** [comment]
> Unfortunately this isn't possible in Django, since routing can be done by arbitrary code and isn't just 'per app' or 'per model'. In general the advice is to keep your database config relatively simple, so I'm fine with checking that all MySQL databases in the config are compatible. If someone's running their app on multiple MySQL versions they're going to cause more pain than just this check (which can be silenced in the usual Django way).

OK, I understand. Sometimes is not a design decision to have multiple databases, but you are forced to do it when you need to integrate with some legacy system that doesn't offer an API. Just for curiosity: what is the "usual Django way" to silence that check?

Anyway, I started fixing the tests (23 now fail). Only, I need to figure out how to avoid the migrations to be executed on the dummy sqlite3 database.

**Comment by adamchainz** [comment]
https://docs.djangoproject.com/en/1.9/topics/checks/

> If you have inspected the cause of a warning and are happy to ignore it, you can hide specific warnings using the SILENCED_SYSTEM_CHECKS setting in your project settings file.

**Comment by adamchainz** [comment]
Fixed by #281
