### ISSUE TITLE
Override update_or_create with ON DUPLICATE KEY

### ISSUE THREAD

**Issue by cjhenck** [adamchainz/django-mysql#320]
Summary: If you use update_or_create within nested transactions, it's possible to get a race condition that throws an exception.  Supporting MySQL's INSERT ... ON DUPLICATE KEY would remove that possibility.

**Comment by adamchainz** [comment]
`ON DUPLICATE KEY` has tricky semantics because with multiple unique keys on a table it can use any. Also there's a much larger question as to whether Django should support 'upsert' statements in general as Postgres supports them too now.

I remember seeing some stuff on the django mailing list about upserts, I think you should take this there with a new thread or revive a recent one. I don't really want to put a different SQL compiler into Django-MySQL for `ON DUPLICATE KEY`.

**Comment by adamchainz** [comment]
(But I'd try help with an implementation in django core!)

**Comment by cjhenck** [comment]
I saw that the django-postgresql extension had upsert functionality already which is why I added the issue here.  I wouldn't mind reopening the conversation with Django core though! Thanks

**Comment by adamchainz** [comment]
Link? https://pypi.python.org/pypi/django-postgresql isn't very helpful...

**Comment by cjhenck** [comment]
Hmm, I can't find the link anymore.  I guess it wasn't a very well-used package!  Never mind

**Comment by adamchainz** [comment]
Dang.
