### ISSUE TITLE
Allow custom encoder on JSONField

### ISSUE THREAD

**Issue by newmanne** [adamchainz/django-mysql#386]
I'm using the `JSONField` but want to use `django.core.serializers.json.DjangoJSONEncoder` as the encoder. I see that `JSONField` calls `json.dumps(value, allow_nan=False)` in a few places, and this is where I would want to set `cls=DjangoJSONEncoder`. This would take some pain out of JSON fields with dates. I'd suggest an optional argument for encoder to JSONField.

**Comment by adamchainz** [comment]
So we currently use `json.dumps(value, allow_nan=False)` to be completely in-line with what MySQL itself supports. I fear that allowing different encoders in the base field would just confuse what it is supported - you could e.g. have datetimes in python land when manipulating the model, but when you try do a filter like `MyModel.objects.filter(attrs__mydate__gt=timezone.now())` you'd get meaningless results because the dates wouldn't be compared except as strings (but example if you're doing dates as iso8601, but you get the idea).

**Comment by newmanne** [comment]
That's fair. Thanks for responding.
