### ISSUE TITLE
Wrong validation of ListTextField in API requests

### ISSUE THREAD

**Issue by ido567** [adamchainz/django-mysql#390]
Summary:
I've built an API based on [django rest framework](http://www.django-rest-framework.org/) & [django rest framework json api](https://github.com/django-json-api/django-rest-framework-json-api).
One of my models has a list of screenshots as a JSON array:
`screenshots_url = ListTextField(base_field=models.URLField(), size=10)`

Field validations work fine when I change the model by Django admin panel, but it fails when I try to change it by API calls.
It seems like the field is validated as a string instead of an array.

The values that I tried to send by API:
Sent data: `"screenshots_url": "http://test.com/screen.jpg"`
Error: `List contains 26 items, it should contain no more than 10.`

Sent data: `"screenshots_url": ["http://test.com/screen.jpg"]`
Error: `Not a valid string.`

Sent data: `"screenshots_url": "['http://test.com/screen.jpg']"`
Error: `List contains 30 items, it should contain no more than 10.`

Django Version: *Django 1.11.2*

Database and version used: *MySQL 5.7.18*

Version: *Django-MySQL 2.1.0*

DRF Version: *Django Rest Framework 3.6.3*

**Comment by adamchainz** [comment]
`ListTextField` is not a JSON array, it stores things as a comma separated list of strings. It seems to me you need to do some work to make it work with Django Rest Framework, I don't have much experience there so can't help you.

Anyway, I suggest you try `JSONField` instead as that is more likely easy to get working, and less likely to break on you, because of course URL's can contain commas, and they won't be escaped by a `ListTextField(base_field=URLField())`.

**Comment by ido567** [comment]
Is there a way to restrict `JSONField` to be an array and not key value object?

**Comment by adamchainz** [comment]
Add a custom validator function. I guess this would be picked up by DRF too.

**Comment by adamchainz** [comment]
Closing now
