### ISSUE TITLE
Extending JSON field breaks makemigration command

### ISSUE THREAD

**Issue by deveArt** [adamchainz/django-mysql#436]
Summary: I want to extend django_mysql.models.JSONField. But it breaks my futher migrations in the following way:

This is my custom field:
```
from django_mysql.models import JSONField
class JsonExtended(JSONField):
    ...
```

Then in migrations:
```
        migrations.AlterField(
            model_name='task',
            name='params',
            field=django_mysql.models.JsonExtended(default=dict), 
           # but must be ---> path_to_module.JsonExtended(default=dict)
        ),
```

Django Version: 2.0.2
Database and version used: MariaDB 10.2.13
Version:  Django-MySQL 2.2.0

**Comment by adamchainz** [comment]
Probably we should be smarter in the `deconstruct`: https://github.com/adamchainz/django-mysql/blob/master/django_mysql/models/fields/json.py#L82

But you can fix yourself by extending `deconstruct` and making it return the correct `path` for now

**Comment by deveArt** [comment]
Ok for now I will use this solution. Thanks. But I hope you'll improve this functionality :)

**Comment by natecox** [comment]
I just hit this issue today and lost a day debugging it. Until a proper fix makes its way upstream, can we add a big warning to the docs about subclassing?

For reference, here's a list of all the places currently hard-coding the import path for `django_mysql.models`:
![image](https://user-images.githubusercontent.com/2782695/38706943-01adc252-3e64-11e8-8c43-1868367bc241.png)

**Comment by adamchainz** [comment]
Sorry this affected you too @natecox. The fix was in the end fairyl simple, in fact all the other field classes already had correct `deconstruct()` methods, but it was missed in JSONField. There was actually an analogous bug in Django django/django#3765 - I started the fields in Django-MySQL based on the fields in `django.contrib.postgres`, hence this path-simplifying logic was copied over before the fix had been applied to master, I guess I missed applying it to JSONField. Release 2.2.1 is out now with the fix.

> I just hit this issue today and lost a day debugging it. Until a proper fix makes its way upstream, can we add a big warning to the docs about subclassing?

I understand you must have been frustrated you spent so much time tracking down your bug. However, I didn't find this comment particularly motivating, as I read it as a bit 'entitled'. I develop this software entirely in my spare time as a labour of love. I'm sure you appreciate this :)

**Comment by natecox** [comment]
@adamchainz Sorry if you felt I was attacking you, but you might be a bit overly defensive about this. My intention was to let you know that it's a problem and that it would be useful to post instructions about this so it doesn't become a surprise, as in my case.
