### ISSUE TITLE
AttributeError from CharField in ListCharField

### ISSUE THREAD

**Issue by jotauses** [adamchainz/django-mysql#565]
I copy and paste the ListFields example and it return an error:

from django.db.models import CharField, Model
from django_mysql.models import ListCharField

class Person(Model):
    name = CharField()
    post_nominals = ListCharField(
        base_field=CharField(max_length=10),
        size=6,
        max_length=(6 * 11)  # 6 * 10 character nominals, plus commas
    )

ERROR: AttributeError: 'CharField' object has no attribute 'set_attributes_from_name'

MySQL==5.7
Django==2.2.3
django-mysql==3.2.0
mysqlclient==1.4.2

**Comment by adamchainz** [comment]
Please provide a full traceback and don't use non-specific semi-aggressive issue titles like "This library does not work". The library is tested and you can see the test model definition in https://github.com/adamchainz/django-mysql/blob/master/tests/testapp/models.py#L78 looks similar to your intentions.

My *suspicion* is that you may be using Django's form CharField rather than the DB CharField.

**Comment by jotauses** [comment]
Like I said I copy and paste the example code and it does not work. You can see the imports like the example. The CharField comes from Models.

**Comment by adamchainz** [comment]
I can't debug this without a traceback. `set_attributes_from_name` is a method on the base model `Field` so it doesn't seem like it could go missing: https://github.com/django/django/blob/stable/2.2.x/django/db/models/fields/__init__.py#L719

**Comment by adamchainz** [comment]
closing due to age
