### ISSUE TITLE
System check will fail when running unit tests that require no databases

### ISSUE THREAD

**Issue by tinyx** [adamchainz/django-mysql#788]
Summary: 

When running specific Django unit tests that requires no database, it will fail with "unknown database: \<default database name\>". Same thing would happen when running system check `./manage.py check` without the default database being created.

I believe this is because of this line here:
https://github.com/adamchainz/django-mysql/blob/main/src/django_mysql/models/fields/json.py#L83

together with this new behavior since Django 2.2:
https://github.com/django/django/blob/2.2.22/django/test/runner.py#L606

If no databases are used for certain test files/cases, Django will skip the setup process and hence the system check step during tests would fail.

Also this seems to indicate that Django assumes `./manage.py check` should not require a database to work. This is reflected by their description as well: https://docs.djangoproject.com/en/2.2/ref/checks/#system-check-framework

 > The system check framework is a set of static checks for validating Django projects.

Django Version: *Django 2.2.22*

Database and version used: *MySQL 5.7.31*

Version: *Django-MySQL 3.11.1*

**Comment by adamchainz** [comment]
The underlying function iterates over all databases so I'm not sure.

I'm not particularly invested in maintaining the JSONField here, since there's the universal JSONField included in Django 3.1+, and available for older Django versions in [the django-jsonfield-backport package](https://pypi.org/project/django-jsonfield-backport/).

I'd still accept a PR fixing this check, I guess. But I will be removing the Django-MySQL JSONField class at some point in the near future, after Django 2.2 ends support.

**Comment by tinyx** [comment]
Thanks for replying, that sounds reasonable. We are a little far from getting to 3.1 but eventually need to migrate to it as well.

**Comment by adamchainz** [comment]
Ok I will close this for now but if you make a PR you can reference it.
